name: Update BMNR Stock Data

on:
  schedule:
    # í‰ì¼ ë¯¸êµ­ ìž¥ ì‹œê°„(UTC 14:30-21:00) = 2ë¶„ë§ˆë‹¤
    - cron: '*/2 14-21 * * 1-5'
    # ê·¸ ì™¸ í‰ì¼ ì‹œê°„ = 10ë¶„ë§ˆë‹¤
    - cron: '*/10 0-14,21-23 * * 1-5'
    # ì£¼ë§ = 30ë¶„ë§ˆë‹¤
    - cron: '*/30 * * * 0,6'
  workflow_dispatch:

jobs:
  update-stock-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch Stock and Crypto Data
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "ðŸ“… Timestamp: $TIMESTAMP"
          
          echo "ðŸ”„ Fetching Ethereum price..."
          ETH_DATA=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd")
          ETH_PRICE=$(echo $ETH_DATA | jq -r '.ethereum.usd')
          echo "âœ… ETH Price: $ETH_PRICE"
          
          echo "ðŸ”„ Fetching BMNR stock price..."
          STOCK_DATA=$(curl -s "https://api.twelvedata.com/quote?symbol=BMNR&apikey=$TWELVEDATA_API_KEY")
          echo "ðŸ“Š Stock Response: $STOCK_DATA"
          
          STOCK_SYMBOL=$(echo $STOCK_DATA | jq -r '.symbol // "BMNR"')
          STOCK_PRICE=$(echo $STOCK_DATA | jq -r '.close // "29.32"')
          STOCK_CHANGE=$(echo $STOCK_DATA | jq -r '.change // "-2.07"')
          STOCK_PERCENT=$(echo $STOCK_DATA | jq -r '.percent_change // "-6.59"')
          STOCK_PREV_CLOSE=$(echo $STOCK_DATA | jq -r '.previous_close // "31.39"')
          
          echo "âœ… Stock Price: $STOCK_PRICE"
          
          cat > stock_data.json << EOF
          {
            "timestamp": "$TIMESTAMP",
            "ethereum": $ETH_PRICE,
            "stock": {
              "symbol": "$STOCK_SYMBOL",
              "price": "$STOCK_PRICE",
              "change": "$STOCK_CHANGE",
              "percent_change": "$STOCK_PERCENT",
              "previous_close": "$STOCK_PREV_CLOSE"
            }
          }
          EOF
          
          echo "âœ… stock_data.json created"
          cat stock_data.json
      
      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add stock_data.json
          
          if git diff --staged --quiet; then
            echo "â­ï¸ No changes"
          else
            git commit -m "ðŸ”„ Update stock data - $(date -u +"%Y-%m-%d %H:%M UTC")"
            git push
            echo "âœ… Pushed"
          fi
